name: Build Docker Image CI

on:
  push:
    branches:
      - main

env:
  dockerfile: './Dockerfile'
  platform: 'linux/amd64,linux/arm64'
  image_name: 'huggingface-downloader'
  tag: 'latest'
  ci_registry: 'docker.io'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to DockerHub Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ci_registry }}
          username: ${{ secrets.CI_REGISTRY_USERNAME }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ env.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}:${{ env.tag }}
            ${{ secrets.CI_REGISTRY_USERNAME }}/${{ env.image_name }}:${{ env.tag }}
            ${{ secrets.CI_REGISTRY_USERNAME }}/${{ env.image_name }}:${{ github.sha }}
